<!-- Google Analytics Tracking -->
<script type="text/javascript">
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-9589147-7', 'janeullah.com');
  ga('send', 'pageview');

</script>

<!-- End Google Analytics -->

<!-- Start of StatCounter Code for Default Guide -->
<script type="text/javascript">
    var sc_project=8920740; 
    var sc_invisible=1; 
    var sc_security="705da947"; 
    var scJsHost = (("https:" == document.location.protocol) ?
    "https://secure." : "http://www.");
    document.write("<sc"+"ript type='text/javascript' src='" +
    scJsHost+
    "statcounter.com/counter/counter.js'></"+"script>");
</script>
<noscript>
    <div class="statcounter">
        <a title="web counter"
        href="http://statcounter.com/free-hit-counter/"
        target="_blank">
            <img class="statcounter"
        src="http://c.statcounter.com/8920740/0/705da947/1/"
        alt="web counter">
        </a>
    </div>  
</noscript>
<!-- End of StatCounter Code for Default Guide -->
<!-- Quantcast -->
<!-- Quantcast Tag -->
<script type="text/javascript">
var _qevents = _qevents || [];

(function() {
var elem = document.createElement('script');
elem.src = (document.location.protocol == "https:" ? "https://secure" : "http://edge") + ".quantserve.com/quant.js";
elem.async = true;
elem.type = "text/javascript";
var scpt = document.getElementsByTagName('script')[0];
scpt.parentNode.insertBefore(elem, scpt);
})();

_qevents.push({
qacct:"p-40L5AKn-54z3w"
});
</script>

<noscript>
<div style="display:none;">
<img src="//pixel.quantserve.com/pixel/p-40L5AKn-54z3w.gif" border="0" height="1" width="1" alt="Quantcast"/>
</div>
</noscript>
<!-- End Quantcast tag -->
<!-- End Quantcast -->
