<!-- Google Analytics Tracking -->
<script type="text/javascript">
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-9589147-7', 'janeullah.com');
  ga('send', 'pageview');

</script>

<!-- End Google Analytics -->

<!-- Start of StatCounter Code for Default Guide -->
<script type="text/javascript">
    var sc_project=8920740; 
    var sc_invisible=1; 
    var sc_security="705da947"; 
    var scJsHost = (("https:" == document.location.protocol) ?
    "https://secure." : "http://www.");
    document.write("<sc"+"ript type='text/javascript' src='" +
    scJsHost+
    "statcounter.com/counter/counter.js'></"+"script>");
</script>
<noscript>
    <div class="statcounter">
        <a title="web counter"
        href="http://statcounter.com/free-hit-counter/"
        target="_blank">
            <img class="statcounter"
        src="http://c.statcounter.com/8920740/0/705da947/1/"
        alt="web counter">
        </a>
    </div>  
</noscript>
<!-- End of StatCounter Code for Default Guide -->
